### ISSUE TITLE
Addon doesn't work

### ISSUE THREAD

**Issue by Dogeyy** [wiox/gmod-mapvote#4]
Or I'm just really such a noob, or your addon is broken;
I installed ULib and Ulx in my garrysmod/addons directory, and did the same with your addon, I put in the zip file and extracted all the files that are in there, but it is still not working, am I doing something wrong here, or is your addon broken?

**Comment by wiox** [comment]
This addon is a utility for developers. There's a version of this with code to make it run with common gamemodes and ULX @ https://github.com/tyrantelf/gmod-mapvote or http://steamcommunity.com/sharedfiles/filedetails/?id=151583504
